targets:
  $default:
    builders:
      drift_dev:
        options:
          mutable_classes: true
          generate_connect_constructor: true
          sqlite_modules:
            - json1
            - fts5