import 'dart:io';

void main() {
  final lines = <String>[];
  void a(String l) => lines.add(l);

  a("import 'dart:async';");
  a("");
  a("import 'package:lingbi/services/interfaces/i_ai_service.dart';");
  a("import '../core/ai/ai_provider.dart';");
  a("import '../core/ai/ai_response_normalizer.dart';");
  a("import '../core/ai/free_provider.dart';");
  a("import '../core/ai/model_registry.dart';");
  a("import '../core/ai/models/endpoint_config.dart';");
  a("import '../core/ai/provider_factory.dart';");
  a("import '../core/errors/ai_error.dart';");
  a("import 'quota_service.dart';");
  a("");
  a("/// AI 服务 - 管理所有 AI 提供者并负责路由");
  a("/// 所有供应商通过 EndpointConfig 列表管理，通过 ProviderFactory 创建。");
  a("/// 不再持有硬编码 Provider 实例，不再使用 switch(name) 路由。");
  a("class AIService implements IAIService {");
  a("  AIService({required QuotaService quotaService}) : _quota = quotaService;");
  a("  final FreeProvider _freeProvider = FreeProvider();");
  a("  final QuotaService _quota;");
  a("  String _currentProvider = 'free';");
  a("  String _projectContext = '';");
  a("  StreamSubscription<String>? _activeSubscription;");
  a("  bool get isGenerating => _activeSubscription != null;");
  a("  final List<EndpointConfig> _endpoints = [];");
  a("  final Map<String, AIProvider> _providerCache = {};");
  a("  List<EndpointConfig> get endpoints => List.unmodifiable(_endpoints);");
  a("");
  a("  void addEndpoint(EndpointConfig config) {");
  a("    final idx = _endpoints.indexWhere((e) => e.id == config.id);");
  a("    if (idx >= 0) { _endpoints[idx] = config; }");
  a("    else { _endpoints.add(config); }");
  a("    _providerCache.remove(config.id);");
  a("  }");
  a("");
  a("  void removeEndpoint(String id) {");
  a("    _endpoints.removeWhere((e) => e.id == id);");
  a("    _providerCache.remove(id);");
  a("    if (_currentProvider == id) _currentProvider = 'free';");
  a("  }");
  a("");
  a("  EndpointConfig? getEndpoint(String id) {");
  a("    try { return _endpoints.firstWhere((e) => e.id == id); }");
  a("    catch (_) { return null; }");
  a("  }");
  a("");
  a("  @override String get currentProviderName => _currentProvider;");
  a("");
  a("  @override List<AIProvider> get availableProviders {");
  a("    final list = <AIProvider>[_freeProvider];");
  a("    for (final config in _endpoints) {");
  a("      final p = _getOrCreateProvider(config.id);");
  a("      if (p != null && p.isAvailable) list.add(p);");
  a("    }");
  a("    return list;");
  a("  }");
  a("");
  a("  AIProvider get currentProvider {");
  a("    if (_currentProvider == 'free') return _freeProvider;");
  a("    return _getOrCreateProvider(_currentProvider) ?? _freeProvider;");
  a("  }");
  a("");
  a("  AIProvider? _getOrCreateProvider(String configId) {");
  a("    if (_providerCache.containsKey(configId)) {");
  a("      return _providerCache[configId];");
  a("    }");
  a("    final config = getEndpoint(configId);");
  a("    if (config == null) return null;");
  a("    try {");
  a("      final provider = ProviderFactory.create(config);");
  a("      _providerCache[configId] = provider;");
  a("      return provider;");
  a("    } catch (_) { return null; }");
  a("  }");
  a("");
  a("  @override void setProvider(String name) {");
  a("    if (name == 'free' || _endpoints.any((e) => e.id == name)) {");
  a("      _currentProvider = name;");
  a("    }");
  a("  }");
  a("");
  a("  @override void setProjectContext(String context) {");
  a("    _projectContext = context;");
  a("  }");
  a("");
  a("  @override void configureApiKey(String provider, String key) {");
  a("    final idx = _endpoints.indexWhere((e) => e.id == provider);");
  a("    if (idx >= 0) {");
  a("      _endpoints[idx] = _endpoints[idx].copyWith(apiKey: key.isEmpty ? null : key);");
  a("      _providerCache.remove(provider);");
  a("    }");
  a("  }");
  a("");
  a("  List<ChatMessage> _buildMessages(String userMessage) {");
  a("    final messages = <ChatMessage>[];");
  a("    if (_projectContext.isNotEmpty) {");
  a("      messages.add(ChatMessage(role: 'system', content: '当前项目上下文：\n$_projectContext\n\n你是一个专业的写作助手，帮助用户进行小说创作。请基于上述上下文提供帮助。'));");
  a("    } else {");
  a("      messages.add(const ChatMessage(role: 'system', content: '你是一个专业的 AI 写作助手，帮助用户进行小说创作。可以续写、改写、扩写文本，也可以分析结构和风格。'));");
  a("    }");
  a("    messages.add(ChatMessage(role: 'user', content: userMessage));");
  a("    return messages;");
  a("  }");
  a("");
  a("  ModelInfo? get currentModelInfo {");
  a("    return ModelRegistry.instance.findModel(");
  a("      currentProvider.currentModelId,");
  a("      providerId: _currentProvider == 'free' ? null : _currentProvider,");
  a("    );");
  a("  }");
  a("  String get currentModelId => currentProvider.currentModelId;");
  a("  void cancelCurrentRequest() { _activeSubscription?.cancel(); _activeSubscription = null; }");
  a("");
  a("  Stream<String> testGeneration({String? providerId, int maxTokens = 100}) async* {");
  a("    final provider = providerId != null ? _resolveProvider(providerId) : currentProvider;");
  a("    final controller = StreamController<String>();");
  a("    _activeSubscription = provider.chat(");
  a("      messages: const [ChatMessage(role: 'user', content: '请用一句不超过 30 字的中文，描写雨夜中的旧车站。')],");
  a("      maxTokens: maxTokens,");
  a("    ).listen(");
  a("      (chunk) => controller.add(chunk),");
  a("      onError: (Object error) { controller.addError(AiErrorMapper.map(error, provider: providerId ?? _currentProvider)); },");
  a("      onDone: () => controller.close(),");
  a("    );");
  a("    yield* controller.stream;");
  a("    _activeSubscription = null;");
  a("  }");
  a("");
  a("  Future<ConnectionTestResult> testConnection() async {");
  a("    return currentProvider.testConnection();");
  a("  }");
  a("");
  a("  Future<ConnectionTestResult> testConnectionUnified({String? providerId, String? modelId}) async {");
  a("    final pid = providerId ?? _currentProvider;");
  a("    final provider = _resolveProvider(pid);");
  a("    final sw = Stopwatch()..start();");
  a("    try {");
  a("      final resp = await provider.chatSync(messages: [const ChatMessage(role: 'user', content: '只回复：连接成功')], maxTokens: 10);");
  a("      sw.stop();");
  a("      final t = resp.trim();");
  a("      if (t.isEmpty) return ConnectionTestResult(success: false, latencyMs: sw.elapsedMilliseconds, modelId: modelId ?? provider.currentModelId, providerId: pid, message: '收到空响应，请检查模型配置', errorCategory: '空响应');");
  a("      return ConnectionTestResult(success: true, latencyMs: sw.elapsedMilliseconds, modelId: modelId ?? provider.currentModelId, providerId: pid, message: '连接成功', responsePreview: _buildResponsePreview(t));");
  a("    } catch (e) {");
  a("      sw.stop();");
  a("      final cat = _classifyError(e);");
  a("      return ConnectionTestResult(success: false, latencyMs: sw.elapsedMilliseconds, modelId: modelId ?? provider.currentModelId, providerId: pid, message: cat, errorCategory: cat);");
  a("    }");
  a("  }");
  a("");
  a("  String _buildResponsePreview(String response) {");
  a("    final c = response.replaceAll(RegExp(r'[\r\n\t]'), ' ').replaceAll(RegExp(r'[\x00-\x1F\x7F]'), '').trim();");
  a("    if (c.length <= 80) return c;");
  a("    return '\${c.substring(0, 77)}...';");
  a("  }");
  a("");
  a("  String _classifyError(Object e) {");
  a("    final msg = e.toString().toLowerCase();");
  a("    if (msg.contains('401') || msg.contains('unauthorized')) return '密钥无效，请检查 API Key 是否复制完整';");
  a("    if (msg.contains('403') || msg.contains('forbidden')) return '权限不足，请检查账户状态';");
  a("    if (msg.contains('404') || msg.contains('not found')) return '模型不存在，请检查 modelId 配置';");
  a("    if (msg.contains('429') || msg.contains('rate limit')) return '频率限制，请稍后重试';");
  a("    if (msg.contains('balance') || msg.contains('insufficient') || msg.contains('余额')) return '余额不足，请充值后重试';");
  a("    if (msg.contains('socket') || msg.contains('timeout') || msg.contains('connection') || msg.contains('network')) return '网络不可达，请检查网络连接';");
  a("    
