// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `parse_uuid`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`

Future<RustProjectSession> openProject({required String root}) =>
    RustLib.instance.api.crateApiProjectOpenProject(root: root);

Future<int> projectV2SchemaVersion() =>
    RustLib.instance.api.crateApiProjectProjectV2SchemaVersion();

Future<List<RustDocument>> listDocuments({required String root}) =>
    RustLib.instance.api.crateApiProjectListDocuments(root: root);

Future<String> readDocument(
        {required String root, required String documentId}) =>
    RustLib.instance.api
        .crateApiProjectReadDocument(root: root, documentId: documentId);

Future<RustDocument> createDocument(
        {required String root,
        required String projectId,
        required String title,
        required String content}) =>
    RustLib.instance.api.crateApiProjectCreateDocument(
        root: root, projectId: projectId, title: title, content: content);

Future<RustDocument> saveDocument(
        {required String root,
        required String documentId,
        required int expectedRevision,
        required String content}) =>
    RustLib.instance.api.crateApiProjectSaveDocument(
        root: root,
        documentId: documentId,
        expectedRevision: expectedRevision,
        content: content);

class RustAppError implements FrbException {
  final String code;
  final String message;
  final bool retryable;

  const RustAppError({
    required this.code,
    required this.message,
    required this.retryable,
  });

  @override
  int get hashCode => code.hashCode ^ message.hashCode ^ retryable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustAppError &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          message == other.message &&
          retryable == other.retryable;
}

class RustDocument {
  final String id;
  final String projectId;
  final String title;
  final int order;
  final int revision;
  final String contentHash;
  final String createdAt;
  final String updatedAt;

  const RustDocument({
    required this.id,
    required this.projectId,
    required this.title,
    required this.order,
    required this.revision,
    required this.contentHash,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      projectId.hashCode ^
      title.hashCode ^
      order.hashCode ^
      revision.hashCode ^
      contentHash.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustDocument &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          projectId == other.projectId &&
          title == other.title &&
          order == other.order &&
          revision == other.revision &&
          contentHash == other.contentHash &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

class RustProject {
  final String id;
  final String name;
  final int schemaVersion;
  final String createdAt;
  final String updatedAt;

  const RustProject({
    required this.id,
    required this.name,
    required this.schemaVersion,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      schemaVersion.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustProject &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          schemaVersion == other.schemaVersion &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

class RustProjectSession {
  final RustProject project;
  final RustDocument currentDocument;
  final bool dirty;

  const RustProjectSession({
    required this.project,
    required this.currentDocument,
    required this.dirty,
  });

  @override
  int get hashCode =>
      project.hashCode ^ currentDocument.hashCode ^ dirty.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustProjectSession &&
          runtimeType == other.runtimeType &&
          project == other.project &&
          currentDocument == other.currentDocument &&
          dirty == other.dirty;
}
